GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJuYW1lIjoiaGFuZG9rbyIsImVtYWlsIjoiaGFuZG9rbzIwQGdtYWlsLmNvbSIsImlhdCI6MTcxNTgzNDI5NiwiZXhwIjoxNzE1ODM0MzE2fQ.39luDxmK0tw-ndzipNScjIQYE0Sjz0Mfs5VOPHfHYHw
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "handoko",
    "email" : "handoko20@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "handoko20@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###

DELETE http://localhost:5000/logout

