GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJuYW1lIjoiaGFuZG9rbyIsImVtYWlsIjoiaGFuZG9rbzIwQGdtYWlsLmNvbSIsImlhdCI6MTcxNjA5MjU1MiwiZXhwIjoxNzE2MDkyNTcyfQ.zElqVzEl3PgW8HEEZ74Ap43AGOP7_CZj5qdEnfcmgGg
###
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "handoko",
    "email" : "handoko20@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "handoko20@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/contacts